version: '3.9'
services:
  web:
    build: .
    ports:
      - 4000:4000
      - 4001:4001
    environment:
      NODE_ENV: production
    volumes:
      - /usr/src/app/uploads:/app/dist/public
  redis:
    image: arm32v7/redis:5.0.14-alpine
    container_name: cowket-redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server
